### ISSUE TITLE
xml2jsonstruct not working on Windows

### ISSUE THREAD

**Issue by klauern** [wicast/xj2s#1]
I get the following error when trying to run this:

``` powershell
C:\Users\Me
λ xmljson2struct.exe
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x30 pc=0x401c91]

goroutine 1 [running]:
main.main()
        C:/Users/Me/dev/golang/src/github.com/wicast/xj2s/cmd/xmljson2struct/main.go:48 +0x9d1
```

`go version go1.5.1 windows/amd64`

It might have something to do with [this line](https://github.com/wicast/xj2s/blob/master/cmd/xmljson2struct/main.go#L48) using [`ModeCharDevice`](https://godoc.org/os#FileMode), but it's hard to tell.  I haven't used `os.Stat` before in my projects, either, so it could just as likely be that.

**Comment by wicast** [comment]
Fixed,I forget windows can't use stdin for input.

**Comment by klauern** [comment]
Excellent.  Thank you.
